spring:
  application:
    name: verve-guard


  datasource:
    url: jdbc:mysql://localhost:3306/verve_guard?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql


  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: gosmajesty@gmail.com
    password: noaexrabuvxhdbqb
    protocol: smtp
    subject: Gospel's Verve Guard
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

  company:
    name: Gospel's-Switch-Guard

  #FLYWAY PROPERTIES
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true


server:
  port: 9090

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5911}
  expiration-ms: ${JWT_EXPIRATION_MS:900000} # 15 minutes
  refresh-expiration-ms: ${JWT_REFRESH_EXP_MS:604800000} # 7 days

app:
  email-topic: emails

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
    org:
      springframework:
        security: DEBUG
  pattern:
    level: "%5p [traceId=%X{traceId}, spanId=%X{spanId}]"


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces




#retry:
#  max-attempts: 4
#  initial-interval-ms: 500
#  multiplier: 2.0